[WFCORE-5121] Add ability to ignore excluded extensions to FetchMissi…
wildfly/wildfly-core pull request #4322
Opened 2020-09-08 11:32 UTC by spyrkob

JIRA: https://issues.redhat.com/browse/WFCORE-5121

Attempts to solve the issue by passing the domain exclude info used to generate initial sync to handler doing missing config sync. This requires changing visibility of some methods, I'm not sure if there's a better way. 
@jmesnil could you review please?

2020-09-15 07:18 UTC, jmesnil commented
@yersan could you please review?

2020-09-18 11:05 UTC, yersan requested changes
@spyrkob A slightly different approach could be exposing the `HostInfo.domainIgnoredExtensions `and add them as an attachment to the slave host controller channel, then, using the similar approach as you did with the Version, you could get the exclusions on `FetchMissingConfigurationHandler`. That could reduce the coupling and the amount of methods made public. What do you think?

When the slave is connected, the HostInfo gets the domain exclusions for this host. If an exclusion is modified by the user at runtime, then the slave has to be reloaded, but I think that would be fine and expected. Anyway, change an exclusion at runtime does not look like as a common operation.

2020-09-18 13:47 UTC, spyrkob commented
@yersan, thanks I like your idea, it makes this much cleaner :)

I made the changes in separate commit for now, let me know if it looks good and I'll squash them.

2020-09-21 09:08 UTC, yersan approved these changes
Thank you @spyrkob, yes looks good to me too, ready to squash them

2020-09-21 10:34 UTC, spyrkob commented
Done, thanks :)

2020-10-02 10:28 UTC, merged

2020-10-02 10:29 UTC, jmesnil commented
@spyrkob thanks