read-resource operation does not resolve expressions recursively code…
wildfly/wildfly-core pull request #4337
Opened 2020-09-21 16:05 UTC by swetapatra

… and test cases as part of WFCORE-4923

Thanks for submitting your Pull Request!

https://issues.redhat.com/browse/WFCORE-4923

2020-09-21 16:07 UTC, swetapatra commented
@jmesnil @darranl kindly review this,the other branch is somehow corrupted even a Hard reset is not getting it to work,jenkins test cases keep failing on it

2020-09-22 08:19 UTC, jmesnil requested changes

2020-09-22 08:19 UTC, jmesnil commented on controller/src/test/java/org/jboss/as/controller/test/GlobalOperationsTestCase.java
> +        }     }
please fix the code formatting

2020-09-22 10:20 UTC, swetapatra commented
@jmesnil done with the changes squashed it into the same commit as well.

2020-10-01 16:30 UTC, swetapatra commented
@jmesnil @darranl @bstansberry could you kindly review and let me know if any further changes are required?

2020-10-02 03:09 UTC, merged

2020-10-02 03:09 UTC, bstansberry commented
Thanks, @swetapatra