[WFCORE-2687] Addition of getCurrentOperationName() and getCurrentOperationParameter(String name) methods
wildfly/wildfly-core pull request #4356
Opened 2020-10-08 08:47 UTC by lvydra

https://issues.redhat.com/browse/WFCORE-2687

2020-12-04 02:34 UTC, bstansberry requested changes

2020-12-04 02:34 UTC, bstansberry commented on controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
> +        return !(parameterName.equals(NAME) || parameterName.equals(OP) || parameterName.equals(OP_ADDR) || parameterName.equals(OPERATION_HEADERS));
@lvydra Please remove 'parameterName.equals(NAME) 'from this. My apologies; I should not have listed 'name' as an invalid key in the JIRA description. I've corrected the JIRA description.

2020-12-04 02:34 UTC, bstansberry commented on controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
> +    OperationFailedException invalidParameterName(String parameterName);
The return type here should be IllegalArgumentException, as that is what you intend to throw.

2020-12-04 02:34 UTC, bstansberry commented on controller/src/main/java/org/jboss/as/controller/AbstractOperationContext.java
> +            throw new IllegalArgumentException(ControllerLogger.ROOT_LOGGER.invalidParameterName(parameterName));
ControllerLogger.ROOT_LOGGER.invalidParameterName should return IllegalArgumentException so you can just throw what it returns without wrapping.

2020-12-04 02:34 UTC, bstansberry commented on controller/src/main/java/org/jboss/as/controller/OperationContext.java
> +     * @return node for parameter of given name
This should also say 'or {@code null} if the operation has no such parameter'.

2020-12-04 02:34 UTC, bstansberry commented on controller/src/main/java/org/jboss/as/controller/OperationContext.java
> +    ModelNode getCurrentOperationName();
This should return String. The node will always hold a string.

2020-12-04 02:34 UTC, bstansberry commented on controller/src/main/java/org/jboss/as/controller/OperationContext.java
> +     * @param nullable whether return value can be null
whether the return value can be null if the operation has no parameter with the given name

2020-12-04 02:34 UTC, bstansberry commented on controller/src/main/java/org/jboss/as/controller/OperationContext.java
> +     * @return node for parameter of given name
node for the parameter of the given name, or {@code null} if {@code nullable} is {@code true} and the operation has no parameter with the given name

2020-12-04 13:17 UTC, lvydra commented
Hi @bstansberry , thank you for your review. I have added requested changes.

2021-01-28 02:20 UTC, bstansberry approved these changes

2021-01-28 02:20 UTC, bstansberry commented
/retest

2021-01-28 12:14 UTC, merged

2021-01-28 12:14 UTC, bstansberry commented
Thanks, @lvydra !