[WFCORE-5216] jboss-cli.sh script should use eval instead of exec
wildfly/wildfly-core pull request #4421
Opened 2020-12-04 14:54 UTC by istudens

https://issues.redhat.com/browse/WFCORE-5216

2020-12-04 15:17 UTC, jfdenise commented on core-feature-pack/common/src/main/resources/content/bin/jboss-cli.sh
> +    eval \"$JAVA\" $JAVA_OPTS \
We are using exec due to the fix for https://issues.redhat.com/browse/JBEAP-8808.
We can't use eval there. At least in the general case.

2020-12-04 16:21 UTC, jfdenise requested changes
I don't think that the reported problem should be fixed in the jboss-cli script.sh. I asked for more information in the JIRA issue.

2020-12-29 15:03 UTC, DavyKoravand commented
Hi, I would like to add that we also experienced jboss-cli problems due to exec being used after we updated WildFly from v10 to v21. We had issues using JAVA_OPTS parameters that used spaces, even though they were correctly encapsulated by quotes (we tried every escape/quote combination). We currently use a workaround where we make sure that JAVA_OPTS is empty when using the jboss-cli, but it would be nice to see eval being used again.

2021-01-05 15:24 UTC, jfdenise commented
@DavyKoravand , could you provide some JAVA_OPTS values that create problems? Thank-you.

2021-01-07 10:21 UTC, jfdenise commented
@istudens , instead of using eval to launch the CLI process, we should call the following just before to call exec:
JBOSS_MODULEPATH=$(eval "echo $JBOSS_MODULEPATH")
JAVA_OPTS=$(eval "echo $JAVA_OPTS")

2021-01-07 13:30 UTC, istudens commented
@jfdenise ok, I will change the PR accordingly

2021-01-07 16:39 UTC, jfdenise commented
@istudens , it happens that the problem reported with JAVA_OPTS will be fixed differently. Could you update your PR by just adding:
JBOSS_MODULEPATH=$(eval "echo $JBOSS_MODULEPATH")
and forget about the JAVA_OPTS.

2021-01-14 10:41 UTC, istudens commented
I had to toss the testcase modification out as it wasn't working on Windows platform.

2021-01-15 12:20 UTC, jfdenise commented
@istudens , could you make the addition to the test ignored on Windows and kept on other platforms?

2021-01-15 15:08 UTC, istudens commented
I've finally get to the correct `eval` syntax which now even works with special characters in JBOSS_MODULEPATH like '(' etc. However, it is still `eval` which means it might be hacked to execute any arbitrary command if JBOSS_MODULEPATH is set by 
an evil user accordingly.

2021-01-18 08:44 UTC, jfdenise approved these changes
Thank-you, approved.

2021-01-20 10:11 UTC, merged

2021-01-20 10:11 UTC, jmesnil commented
@istudens thanks