[WFCORE-5290] / [WFCORE-5291] / [WFCORE-4584] Elytron Component Upgrades
wildfly/wildfly-core pull request #4481
Opened 2021-02-17 22:30 UTC by fjuma

https://issues.redhat.com/browse/WFCORE-5290
https://issues.redhat.com/browse/WFCORE-5291
https://issues.redhat.com/browse/WFCORE-4584

        Release Notes - WildFly Elytron - Version 1.15.0.CR1
        
<h2>        Component Upgrade
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2068'>ELY-2068</a>] -         Upgrade to MicroProfile JWT 1.2
</li>
</ul>
                    
<h2>        Requirement
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1842'>ELY-1842</a>] -         Update the tool to support generating and exporting / importing a secret key to the credential store
</li>
</ul>
                                                                                                                                                                                                
<h2>        Feature Request
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2081'>ELY-2081</a>] -         Develop a simple properties based credential store for secret keys
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2086'>ELY-2086</a>] -         Update the WildFly Elytron tool to support encrypting clear text values
</li>
</ul>
        
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-1626'>ELY-1626</a>] -         Programmatic web authentication (HttpServletRequest.login()) does not trigger sso
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2076'>ELY-2076</a>] -         Some traces of &quot;programatic&quot; remain in code that should be converted to &quot;programmatic&quot;
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2077'>ELY-2077</a>] -         Due to mechanism wrapping calls to dispose() are not making it to the underlying mechamims,
</li>
<li>[<a href='https://issues.redhat.com/browse/ELY-2087'>ELY-2087</a>] -         Error code 12000 has been duplicated
</li>
</ul>
        
<h2>        Task
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2055'>ELY-2055</a>] -         Refactor CredentialStoreCommand to make development easier
</li>
</ul>
                
<h2>        Release
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELY-2089'>ELY-2089</a>] -         Release WildFly Elytron 1.15.0.CR1
</li>
</ul>
                                        

        Release Notes - Elytron Web - Version 1.9.0.CR1
        
<h2>        Component Upgrade
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-120'>ELYWEB-120</a>] -         Update Undertow to 2.2.3.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-121'>ELYWEB-121</a>] -         Upgrade to org.apache.httpcomponents:httpcore:4.4.14
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-122'>ELYWEB-122</a>] -         Upgrade to org.apache.httpcomponents:httpclient:4.5.13
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-123'>ELYWEB-123</a>] -         Upgrade WildFly Elytron to 1.14.1.Final
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-127'>ELYWEB-127</a>] -         Upgrade WildFly Elytron to 1.15.0.CR1
</li>
</ul>
    
<h2>        Enhancement
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-125'>ELYWEB-125</a>] -         Make it possible to pass through an alternative IdentityCache Supplier
</li>
</ul>
                                                                                                                                                                                                                        
<h2>        Bug
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-118'>ELYWEB-118</a>] -         Update Elytron Web to build on Fedora 33
</li>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-126'>ELYWEB-126</a>] -         Programmatic authentication is misspelt as &quot;Programatic&quot; 
</li>
</ul>
        
<h2>        Task
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-119'>ELYWEB-119</a>] -         Create GitHub CI Workflow
</li>
</ul>
                
<h2>        Release
</h2>
<ul>
<li>[<a href='https://issues.redhat.com/browse/ELYWEB-128'>ELYWEB-128</a>] -         Release Elytron Web 1.9.0.CR1
</li>
</ul>

2021-02-18 08:17 UTC, jmesnil requested changes
@fjuma Could you please add a license for this new dependency (near https://github.com/wildfly/wildfly-core/blob/37f67b88a7fd91b1388784368ae2da4a59c993d1/core-feature-pack/common/src/main/resources/license/core-feature-pack-common-licenses.xml#L1140)?

2021-02-18 09:37 UTC, darranl commented
@fjuma FYI I have pulled in the component upgrade commits into my topic branch - if you could please add the licence information as an additional commit so the two PRs can coexist.

2021-02-18 14:12 UTC, fjuma commented
Added the license information.

2021-02-19 14:51 UTC, jmesnil approved these changes

2021-02-19 15:26 UTC, merged

2021-02-19 15:26 UTC, jmesnil commented
@fjuma thanks!