WFCORE-5263 Update all projects with a dependency on wildfly-elytron to use individual modules
wildfly/wildfly-core pull request #4528
Opened 2021-03-16 12:46 UTC by parsharma

Issue: https://issues.redhat.com/browse/WFCORE-5263

2021-03-16 12:48 UTC, parsharma commented
Still work is going on. I have raised this PR before the whole changes to test if anything is breaking because of it.

2021-03-22 16:25 UTC, jmesnil commented
@parsharma I'll put this PR on hold to avoid merging until it is ready.

Please add a comment when you need a review.

2021-04-07 11:12 UTC, parsharma commented
@jmesnil the work is done. PR is ready for review. Thanks

2021-04-08 14:14 UTC, jmesnil commented
@fjuma or @darranl could you please review?

2021-04-09 17:36 UTC, fjuma requested changes
Thanks for working on this @parsharma! It looks like there are a few more places where the dependency on wildfly-elytron should be removed:

* pom.xml
* core-feature-pack/common/pom.xml
* elytron/pom.xml

2021-04-09 17:36 UTC, fjuma commented on testsuite/pom.xml
> +            <artifactId>wildfly-elytron</artifactId>
This should be removed.

2021-04-14 19:29 UTC, parsharma commented
@fjuma I have not removed elytron dependency from parent/pom.xml because of transitive dependencies.

2021-04-14 21:29 UTC, fjuma commented
Thanks for the update @parsharma! To be able to remove the `org.wildfly.security:wildfly-elytron` dependency from the main `pom.xml`, I think we will also need to add an exclusion to the `org.jboss.remoting:jboss-remoting` and the `org.jboss.remotingjmx:remoting-jmx` dependencies in the main `pom.xml` and then work through the compilation errors that occur. From a quick look at the initial compilation failures that will result, it appears that the `domain-management/pom.xml` is missing dependencies on individual Elytron modules.

2021-04-16 15:47 UTC, fjuma commented
Thanks very much for the updates @parsharma! The WildFly Core testsuite is now passing - that's great! The WildFly full testsuite is now failing because the `org.wildfly.security:wildfly-elytron` dependency is no longer available. To get that to pass, the next step would be to work on [WFLY-14377](https://issues.redhat.com/browse/WFLY-14377) which involves updating WildFly to depend on the individual Elytron modules instead of `wildfly-elytron`.
 
We have a couple options on how to proceed:

Option 1: Work on and then merge the changes for WFLY-14377 first in order to get CI to pass for this PR.
Option 2: Now that we know all the missing dependencies on individual Elytron modules have been added where needed in this PR, we could temporarily add back the `org.wildfly.security:wildfly-elytronwildfly-elytron` dependency to the main pom.xml here to get CI passing for this PR in order to merge it. We could then work on the changes for WFLY-14377 and then finally remove the `wildfly-elytron` dependency from the main pom.xml for WildFly Core after that.

@darranl Which option do you prefer?

2021-04-16 17:28 UTC, darranl commented
Thanks for the ping @fjuma 

Something I am going to be starting some discussions on separately is how we can cut down on code going stale in long running PRs - so on that basis I think option 2, get this merged and then we come back for the final clean up.  As this PR has touched a number of poms there is a very serious risk other PRs will introduce conflicts if this sits too long.  Git is strong in many places, concurrent modifications to XML files is not one of those strengths!

We have a lot of other clean up work that is likely to be iterative anyway so this will not be the first.

Thank you for all the contributions @parsharma this is really good to have WildFly Core tackled.

2021-04-16 17:59 UTC, fjuma commented
+1

I've created [WFCORE-5374](https://issues.redhat.com/browse/WFCORE-5374) to track removing the `wildfly-elytron` dependency from the main pom.xml.

2021-04-19 13:24 UTC, darranl commented
@parsharma are we ready to take the hold label off this one?  I assume once CI passes we are ready for final review and merge.

2021-04-19 15:07 UTC, fjuma requested changes
Just have one small comment. The rest looks good to me. Thanks @parsharma!

2021-04-19 18:34 UTC, fjuma approved these changes
Thanks @parsharma!

2021-04-21 09:18 UTC, merged