[WFCORE-5285] Utilize org.wildfly.common.Assert for Null-Checks (cli)
wildfly/wildfly-core pull request #4550
Opened 2021-04-06 20:22 UTC by boris-unckel

Fixing https://issues.redhat.com/browse/WFCORE-5285

Original PR was too big to verify. It has been splitted up, here: cli

2021-04-09 08:03 UTC, jmesnil requested changes

2021-04-09 13:17 UTC, boris-unckel commented
@jmesnil all tests are successful, except "Full integration - Windows" but the failed single test is not related. Please check for approval.

2021-04-09 13:19 UTC, boris-unckel commented on cli/src/main/java/org/jboss/as/cli/impl/CommandContextImpl.java
> +     * Constructor called from Boot invoker, minimal configuration.
@jmesnil One little question to do the workflow right: Should I press "Resolve conversation" after submitting the fix, or do you do it after checking the code?

2021-04-12 07:50 UTC, jmesnil approved these changes

2021-04-13 07:47 UTC, merged