[WFCORE-5409]: Upgrade JGit to 5.11.1.202105131744-r
wildfly/wildfly-core pull request #4594
Opened 2021-05-17 08:34 UTC by ehsavoie

* upgrading JGit to 5.11.1.202105131744-r
 * upgrading Apache SSH to 2.6.0

Jira: https://issues.redhat.com/browse/WFCORE-5409

2021-05-18 09:39 UTC, darranl commented
@ehsavoie FYI the test failures on this one appear directly related to the component upgrade.

2021-06-08 13:14 UTC, jmesnil approved these changes

2021-06-08 13:15 UTC, jmesnil requested changes

2021-06-08 13:15 UTC, jmesnil commented on pom.xml
> +        <version.com.io7m.xom>1.2.10</version.com.io7m.xom>
why was this version added?

2021-06-08 15:03 UTC, jmesnil approved these changes

2021-06-09 07:19 UTC, merged

2021-06-09 07:20 UTC, jmesnil commented
@ehsavoie thanks