[WFCORE-5464] Upgrade JBoss Modules and test expressions resolved fro…
wildfly/wildfly-core pull request #4633
Opened 2021-06-15 12:24 UTC by kabir

…m env vars

Opening as a draft PR just to get it out there
This needs a release of DMR including https://github.com/jbossas/jboss-dmr/pull/38.

https://issues.redhat.com/browse/WFCORE-5464

2021-06-15 14:57 UTC, jmesnil requested changes
Code looks good to me.
The commit message mentions JBoss Modules instead of JBoss DMR.

2021-06-15 15:35 UTC, kabir commented
> Code looks good to me.
> The commit message mentions JBoss Modules instead of JBoss DMR.

Oops - fixed

2021-08-25 14:03 UTC, jmesnil approved these changes

2021-08-25 15:28 UTC, merged

2021-08-25 15:28 UTC, jmesnil commented
@kabir thanks!