WFCORE-5493: Invoke DeploymentTransformer in operation "full-replace-…
wildfly/wildfly-core pull request #4644
Opened 2021-06-30 13:19 UTC by fanste

…deployment"

https://issues.redhat.com/browse/WFCORE-5493

2021-07-02 13:21 UTC, ehsavoie requested changes
I think the code should be shared instead of being copied from DeploymentAddHandler

2021-07-02 13:22 UTC, ehsavoie commented
@jfdenise  may you take a look please ?

2021-07-02 13:47 UTC, fanste commented
> 
> 
> I think the code should be shared instead of being copied from DeploymentAddHandler

New superclass that is used by `DeploymentAddHandler` and `DeploymentFullReplaceHandler`?

`addFromContentAdditionParameter` is slightly different in both handlers. The only methods, that could be extracted are `loadDeploymentTransformer` and `doTransformation` and of course the variable `deploymentTransformer`.

2021-07-02 14:40 UTC, ehsavoie commented
I was thinking of all the transformation code: loading the transformer / transforming in some utility class like DeploymentHandlerUtil

2021-07-05 08:33 UTC, jfdenise commented
+1 for the Utility class.

2021-07-08 16:37 UTC, fanste commented
For the case, that no notification was sent out for my changes: I've moved the common code to a new utility class.

2021-07-09 14:55 UTC, jfdenise commented on server/src/main/java/org/jboss/as/server/deployment/DeploymentTransformationUtil.java
> +public class DeploymentTransformationUtil {
Generally xxxUtil class only expose static methods. I would rename it to DeploymentTransformation, instance of this class has a state (the transformer).

2021-07-22 21:02 UTC, bstansberry commented on server/src/main/java/org/jboss/as/server/deployment/DeploymentTransformation.java
> +public class DeploymentTransformation {
Please make this class package-protected. Thanks :)

2021-09-15 10:09 UTC, fanste commented
Rebased the PR and applied the change as requested by @bstansberry

2021-09-16 20:16 UTC, bstansberry commented
/ok-to-test

2021-09-16 20:18 UTC, bstansberry approved these changes

2021-09-24 09:06 UTC, merged

2021-09-24 09:07 UTC, jmesnil commented
@fanste thanks

2023-09-20 21:50 UTC, bstansberry commented
@fanste 

The WildFly project would like to change its license from the GNU Lesser General Public License version 2.1 to the Apache Software License 2.0. We feel that ASL 2.0 is a better option for the project and our user community, as we find a project's use of LGPL can be a barrier to adoption in some parts of the software community, while we see no such barriers from use of ASL.

Do you agree to a relicensing of your contributions to the WildFly, WildFly Core or JBoss AS 7 projects from LGPL 2.1 to ASL 2.0?

I'm happy to answer any questions you may have about this, and I hope you are doing well. Thank you for your contributions to WildFly and open source!

Best regards,
Brian Stansberry
WildFly Project Lead