WFCORE-5537 Improve error messages in LayersTest
wildfly/wildfly-core pull request #4710
Opened 2021-08-17 16:42 UTC by parsharma

Issue: https://issues.redhat.com/browse/WFCORE-5537

2021-08-19 11:41 UTC, bstansberry requested changes
The "ERROR, some modules have not been provisioned: " message should also be improved.

2021-08-19 11:41 UTC, bstansberry commented on testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
>              throw new Exception("Some unreferenced modules are un-expected " + invalidUnref);
This should still provide some context, e.g. the path to the 'test-standalone-reference' and 'test-all-layers' installations that were compared, e.g.

"Some unreferenced modules in installation <path to test-all-layers> are unexpected compared to <path to test-standalone-reference> -- "

2021-08-20 18:37 UTC, bstansberry commented on testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
>              throw new Exception("Some unreferenced modules are un-expected " + invalidUnref);
@parsharma I meant in the exception message.

2021-08-20 18:38 UTC, bstansberry commented on testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
>              throw new Exception("Some unreferenced modules are un-expected " + invalidUnref);
@parsharma I meant in the exception message.

2021-08-24 06:33 UTC, parsharma commented
Thanks, @bstansberry.

2021-08-24 21:21 UTC, bstansberry commented on testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
> +                    " Some unreferenced modules in installation [path to test-all-layers] are unexpected compared to [path to test-standalone-reference] " + invalidUnref);
Those should be the actually paths.

2022-02-18 00:37 UTC, closed without merging