[WFCORE-5842] [primary/secondary] Bump the xsd to 20.0 due to documen…
wildfly/wildfly-core pull request #5068
Opened 2022-04-22 07:04 UTC by moulalis

Issue: https://issues.redhat.com/browse/WFCORE-5842

2022-04-22 07:06 UTC, moulalis commented on server/src/main/resources/schema/wildfly-config_20_0.xsd
> +           xmlns="urn:jboss:domain:19.0"
@yersan this also be changed to 20.0 in this scope?

2022-04-25 08:37 UTC, jmesnil commented
@moulalis could you specify what are the documentation changes? Could you also paste or attached a diff between the XSD files to help figuring out what changed? thanks

2022-04-25 09:01 UTC, darranl commented
Actually if we have modifications to the schema can we please split them into their own commit otherwise when using IDEs and command line tools we will not be able to detect what happened.

WildFly Core may need a schema bump for other reasons but a documentation change doesn't sound like a sufficient justification unless there is also a change in behaviour.

2022-04-25 10:41 UTC, yersan commented
> WildFly Core may need a schema bump for other reasons but a documentation change doesn't sound like a sufficient justification unless there is also a change in behaviour.

Hi @darranl , thanks for pointing it out. The original intention of this PR was just to adapt the wrong language usage used in the XSD (e.g "fetch-from-master" admin only policy value), however, the analysis doc of the related feature revealed we will need to adapt the parsers to accept "fetch-from-master" and "fetch-from-domain-controller, so it became in a non-only documentation issue.

The changes to adapt the parsers will be tracked on a different Jira. Now I'm wondering if all should be addressed by this one (WFCORE-5842) but using different commits to separate the changes. Feel free to suggest, otherwise, we will continue handling two Jiras.

2022-04-26 06:12 UTC, moulalis commented
> @moulalis could you specify what are the documentation changes? Could you also paste or attached a diff between the XSD files to help figuring out what changed? thanks

@jmesnil PFA screenshots of the differences. https://docs.google.com/document/d/10JWg75ASnR5wE2PMytaEp1I0PbHI_UvZfyEyxZEoPks/edit#heading=h.uffl05i85a9a is the reference document.

![Screenshot1](https://user-images.githubusercontent.com/59642466/165233661-2ff8730d-e0bc-49f0-a1d4-d96fa7dc7984.png)
![Screenshot3](https://user-images.githubusercontent.com/59642466/165233666-ca9b1689-0e2d-49eb-bcc2-c9de9c7f5f10.png)
![Screenshot 2](https://user-images.githubusercontent.com/59642466/165233668-2cc8287c-4a2e-4035-b41d-59668344870c.png)
![Screenshot 4](https://user-images.githubusercontent.com/59642466/165233671-f6e1ca0a-a839-4207-b725-4777c584e1e1.png)
![Screenshot 5](https://user-images.githubusercontent.com/59642466/165233673-06c9e4a3-8361-4215-ba3f-f237c370316d.png)
![Screenshot 6](https://user-images.githubusercontent.com/59642466/165233675-cc7f4117-01d0-4827-8844-4d30880e9c69.png)
![Screenshot 7](https://user-images.githubusercontent.com/59642466/165233679-6cb9ddc4-b7e6-439d-9587-0239bcc18c61.png)
![Screenshot 8](https://user-images.githubusercontent.com/59642466/165233681-7ec77349-af24-4e7a-8b64-eee896238817.png)

2022-04-26 09:11 UTC, darranl commented
@moulalis please split this into two commits so we have access to the history in the future.

2022-04-26 14:00 UTC, jmesnil requested changes
@moulalis none of the changes you made impact the schema. There is no need to bump them if only the doc is updated.

The doc can be updated in the existing 19.0 schema and we will bump it when the structure of the schema is effectively changed.

2022-05-05 12:07 UTC, yersan commented
As discussed internally with @moulalis , closing this for now, we will open a different one including a replacement of fetch-from-master with fetch-from-domain-controller (WFCORE-5901)

2022-05-05 12:07 UTC, closed without merging