WFCORE-5897 [primary/secondary] Problematic Language usage deprecation and replacement in testsuite
wildfly/wildfly-core pull request #5108
Opened 2022-05-24 09:35 UTC by parsharma

Issue: https://issues.redhat.com/browse/WFCORE-5897

2022-05-27 17:17 UTC, yersan commented
Hi @parsharma , I would say we need to split the changes into at least three commits as described in the main issue. We should not add any change unrelated to each point, for example, do not change elytron security user names or auth contexts, or variable names, or whatever is not forced to be changed for each main point, just focus on the three points:

1. Renaming the host-[master/slave].xml configuration files
2. Rename the default DC hostname
3. Rename properties used in the configuration files

That will ensure we are changing the tests accordingly and ensure we are not introducing wrong behaviors.

2022-07-20 12:24 UTC, yersan requested changes
In addition to the above, there are still some uses of unexpected host names in the following classes that should be part of the work done renaming the host names:

```
src/main/java/org/jboss/as/test/integration/management/extension/blocker/BlockerExtension.java:                    name = "master";
src/main/java/org/jboss/as/test/integration/management/extension/error/ErrorExtension.java:                        name = "master";
src/main/java/org/jboss/as/test/integration/management/extension/error/ErrorExtension.java:                                boolean induceOOME = false; // = context.getProcessType().isServer() && !"master".equals(targetHost.asString());
src/main/java/org/jboss/as/test/integration/management/extension/optypes/OpTypesExtension.java:                    String name = hosts.size() > 1 ? "master": hosts.iterator().next();
src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java:                new FilePermission(targetPath.resolve("domains").resolve("JmxControlledStateNotificationsTestCase").resolve("master").resolve("target").toAbsolutePath().toString(), "read, write"),
src/main/java/org/wildfly/test/jmx/ServiceActivatorDeploymentUtil.java:                new FilePermission(targetPath.resolve("domains").resolve("JmxControlledStateNotificationsTestCase").resolve("master").resolve("target").toAbsolutePath().toString() + File.separatorChar + '-', "read, write"),
```

2022-07-20 12:24 UTC, yersan commented on testsuite/domain/src/test/resources/host-configs/host-secondary.xml
> +      name="secondary">
Check HcExtensionAndSubsystemManagementTestCase#checkSlaveReconnected, it looks like it is using a wrong host name

2022-07-21 07:23 UTC, parsharma commented
@yersan, I have removed ModelDescriptionConstants.MASTER and there are 3 classes using MASTER so I have changed it with String "master".

2022-07-21 08:24 UTC, yersan requested changes
Hi @parsharma , would you mind reviewing [my last comment](https://github.com/wildfly/wildfly-core/pull/5108#pullrequestreview-1044858446)? it seems you missed it. 

Let me know when it's ready to review; in addition, check if your custom integration Jobs are passing after applying the changes, thanks

2022-07-21 08:24 UTC, yersan commented on core-model-test/framework/src/main/java/org/jboss/as/core/model/test/CoreModelTestDelegate.java
> +            model = model.require(CHILDREN).require(HOST).require(MODEL_DESCRIPTION).require("master");
It looks like you missed my [comment](https://github.com/wildfly/wildfly-core/pull/5108#pullrequestreview-1044858446);  this should be replaced by "primary"

2022-07-21 08:24 UTC, yersan commented on core-model-test/tests/src/test/java/org/jboss/as/core/model/test/host/ServerConfigTestCase.java
> +        PathAddress pa = PathAddress.pathAddress(PathElement.pathElement(HOST, "master"), PathElement.pathElement(SERVER_CONFIG, "server-four"));
It looks like you missed my [comment](https://github.com/wildfly/wildfly-core/pull/5108#pullrequestreview-1044858446);  this and the others on the same class should be replaced by "primary"

2022-07-21 08:24 UTC, yersan commented on host-controller/src/main/java/org/jboss/as/host/controller/discovery/S3Discovery.java
> +            writeToFile(data, "master");
This one is OK, we will handle S3Discovery.java in a different Jira.

2022-07-21 10:13 UTC, parsharma commented
> CoreModelTestDelegate
> ServerConfigTestCase

These two classes are not the part of test suite so I think we should not change it to primary.

2022-07-22 09:07 UTC, parsharma commented
@yersan PR is ready for review. Only two test cases are failing in the integration jobs [CI Job](https://ci.wildfly.org/buildConfiguration/WildFlyCore_PullRequest_WildFlyCoreFullIntegrationLinuxJdk11_2/316451?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true)

2022-07-27 12:16 UTC, yersan commented
@parsharma The integration job failures need to be corrected on the WildFly full PR.

2022-08-15 23:11 UTC, luck3y commented
/ok-to-test

2022-08-18 06:14 UTC, parsharma commented
Wildfly PR: https://github.com/wildfly/wildfly/pull/15613

2022-09-07 10:09 UTC, yersan requested changes
> @yersan
> 
> > CoreModelTestDelegate
> > ServerConfigTestCase
> 
> These two classes are not the part of test suite so I think we should not change it to primary.

These tests are part of `wildfly-core-model-test-framework`, which is used in the testsuite (both in WildFly Full and Core) we have to change them together with this PR to avoid the need of doing another integration between changes in WildFly Core that requires changes in full.

2022-09-09 12:12 UTC, yersan approved these changes
LGTM, I'm just only waiting to see the result of an integration Job in Windows. 
@parsharma would you mind adding the Jira number to all the commits? Having a Jira number there is very useful when you are looking for the reason for a change in the GitHub history. 

There is no need to trigger the CI Integration jobs again.

Linux: https://ci.wildfly.org/viewLog.html?buildId=324460
Windows: https://ci.wildfly.org/viewLog.html?buildId=324659

2022-09-09 12:34 UTC, parsharma commented
@yersan changes are done. Thanks

2022-09-12 10:36 UTC, merged