[WFCORE-6094] Increase LayersTest timeout
wildfly/wildfly-core pull request #5249
Opened 2022-10-20 08:49 UTC by lvydra

https://issues.redhat.com/browse/WFCORE-6094

2022-10-21 09:03 UTC, yersan requested changes

2022-10-21 09:03 UTC, yersan commented on testsuite/shared/src/main/java/org/jboss/as/test/layers/LayersTest.java
> +            executor.submit(r).get(2, TimeUnit.MINUTES);
Hello @lvydra , would you mind using [TimeoutUtil.java](https://github.com/wildfly/wildfly-core/blob/main/testsuite/shared/src/main/java/org/jboss/as/test/shared/TimeoutUtil.java) for handling this timeout?

This utility class allows timeouts to be modified with a correction factor. Slow CI environments can append the `ts.timeout.factor` property to increase the default timeout, making the testsuite more reliable in slow environments.

Thanks

2022-10-31 17:58 UTC, yersan requested changes
Sadly this is going to need changes in wildfly full before merging this. The test case is complaining about a missing dependency for the test scope for the testsuite/layers module:

org.wildfly.security.manager.WildFlySecurityManager

2022-11-03 13:46 UTC, lvydra commented
Hi @yersan, I have opened PR in wildfly which adds the dependency.

2022-11-07 10:23 UTC, yersan approved these changes
Thanks @lvydra , it is green now

2022-11-08 13:23 UTC, merged