[WFCORE-6135] AbstractConfigurationChangesTestCase - make NPE fastfail
wildfly/wildfly-core pull request #5293
Opened 2022-11-25 15:37 UTC by boris-unckel

Fixes https://issues.redhat.com/browse/WFCORE-6135

2022-12-20 11:07 UTC, yersan requested changes
Hello @boris-unckel , most of the changes here are changing how the cleanup tasks are executed. It is expected that those cleanup tasks are executed independently of whether they cannot be executed because of null variables. 

In such a hypothetical case, we should fail, however by applying these changes we no longer fail, we will silently continue without checking whether the cleanup routine is executed, making the test weaker.

Could you also describe a bit more how `AdminOnlyModeTestCase` would help you with the https://issues.redhat.com/browse/WFCORE-6135 description?

2022-12-21 20:47 UTC, boris-unckel commented
@yersan Thanks for the detailed review. I'm going to fix the issues tomorrow. I want to bring one thing to your attention: BeforeClass and AfterClass are independent. Regardless whether BeforeClass breaks or not, AfterClass is called. You can't assume from the broken state of BeforeClass to the beginning of AfterClass. 

I agree that things which cause an error today should not be silent: This change will cause failures (as term of JUnit) then.

2022-12-22 08:19 UTC, boris-unckel commented
> In such a hypothetical case, we should fail, however by applying these changes we no longer fail, we will silently continue without checking whether the cleanup routine is executed, making the test weaker.

Yes, agreed: A test failing today with a late error shall fail with an early failure after the change. The test keeps strong, respecting Before/After behaviour and making implicit assumptions explicit.

> 
> Could you also describe a bit more how `AdminOnlyModeTestCase` would help you with the https://issues.redhat.com/browse/WFCORE-6135 description?

I have updated the description, adding the current situation, describing the JUnit behaviour. I have changed the solution proposal, to respect the discussed issues.

2022-12-22 12:57 UTC, boris-unckel commented on testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/OperationTimeoutTestCase.java
> +        if (primaryClient != null) {
BeforeClass and AfterClass are independent, if primaryClient creation fails in BeforeClass, the AfterClass will still be called. For the next comments I'm going to refer this with "Before/After independence".
NullCheck turned to assertion.

2022-12-22 12:57 UTC, boris-unckel commented on testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/events/JmxControlledStateNotificationsTestCase.java
> +        if (domainPrimaryLifecycleUtil != null) {
"Before/After independence". NullCheck turned to assertion.

2022-12-22 13:02 UTC, boris-unckel commented on testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/management/HttpManagementConstantHeadersTestCase.java
> +      assertNotNull(domainSecondaryLifecycleUtil);
In general I agree and have done so, but in this case domainSecondaryLifecycleUtil is not in use for every test.

2022-12-22 13:04 UTC, boris-unckel commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ManagementOpTimeoutTestCase.java
> +        if (cli != null) {
Fixed with assertion.

2022-12-22 13:05 UTC, boris-unckel commented on testsuite/rbac/src/test/java/org/jboss/as/test/integration/mgmt/access/AbstractPropertiesRoleMappingTestCase.java
> +            if (managementClient != null) {
Fixed with assertion.

2022-12-22 13:06 UTC, boris-unckel commented on testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/AbstractConfigurationChangesTestCase.java
> +        }
"Before/After independence". NullCheck turned to assertion.

2022-12-22 13:06 UTC, boris-unckel commented on testsuite/domain/src/test/java/org/jboss/as/test/integration/domain/DomainControllerMigrationTestCase.java
> +        }
Fixed with assertion.

2022-12-22 15:20 UTC, boris-unckel commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/auditlog/AuditLogBootingLogTestCase.java
> +        Assert.assertTrue(container.isStarted()); // if container is not started, we get a NPE in container.getClient()
Fixed - I have removed it from the ```@Before``` cases.

2022-12-22 15:24 UTC, boris-unckel commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/logging/LoggingPreferencesTestCase.java
>          container.start();
This is again the preference for failure instead of error for tests, making state assumptions explicit.

2022-12-22 15:25 UTC, boris-unckel commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ManagementOpTimeoutTestCase.java
> +        Assert.assertNotNull(cli); // prevent subsequent NPEs in tests
Fixed, removed.

2022-12-23 11:30 UTC, yersan requested changes

2022-12-23 12:52 UTC, boris-unckel commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/cli/ManagementOpTimeoutTestCase.java
> +        if (cli != null) {
Thanks for the explanation. I have changed it to assertions.

2023-01-17 09:59 UTC, yersan approved these changes

2023-01-17 17:54 UTC, merged

2023-01-17 17:55 UTC, yersan commented
@boris-unckel , thanks!