WFCORE-6185 Upgrade github actions to avoid github action warnings
wildfly/wildfly-core pull request #5341
Opened 2022-12-21 21:02 UTC by chengfang

https://issues.redhat.com/browse/WFCORE-6185

2022-12-22 11:03 UTC, yersan requested changes
[.github/workflows/dep-diff-workflow_run.yml:79](https://github.com/wildfly/wildfly-core/pull/5341/files#diff-ad94be860a27165f4cbeb807c2244579532034e861dc261465dcea1bf4b2c947R39) must be also changed to `var download = await github.rest.actions.downloadArtifact`

For the sake of completeness, can you also upgrade [actions/stale@v3](https://github.com/wildfly/wildfly-core/blob/main/.github/workflows/stale.yml#L12) to v7?

2022-12-22 14:55 UTC, chengfang commented
changed to `github.rest.actions.downloadArtifact` and stale@v7.

2022-12-23 08:30 UTC, yersan approved these changes

2022-12-23 11:40 UTC, merged

2022-12-23 11:41 UTC, yersan commented
@chengfang , thanks!