[WFCORE-6214] Fixed Flaky Test HelpSupportTestCase.testStandalone
wildfly/wildfly-core pull request #5366
Opened 2023-01-30 03:56 UTC by RishabhPrabhu5

### What is the purpose of this PR

- This PR fixes the error resulting from the flaky test `org.jboss.as.cli.impl.aesh.HelpSupportTestCase`
- The mentioned test may fail or pass without changes made to the source code when it is run in different JVMs due to `HashSet`'s non-deterministic iteration order.

### Why the test fails

- `HelpSupportTestCase` calls `SynopsisGenerator`, which uses a `HashSet` as its data structure for the conflicts object. As per Java 11 documentation, the ordering of `HashSet` is not constant, so assigning the same `HashSet` as an array to different objects can change the ordering. So, when comparing these two arrays with `assertEquals` the test may fail as the given order can be different from the expected order.

### Reproduce the test failure

- Run the test with `NonDex` maven plugin. The command to recreate the flaky test failure is
   `mvn -pl cli edu.illinois:nondex-maven-plugin:2.1.1:nondex - 
    Dtest=org.jboss.as.cli.impl.aesh.HelpSupportTestCase#testStandalone`
- Fixing the flaky test now may prevent flaky test failures in future Java versions.

### Expected result

- The tests should run successfully when run with `NonDex`.
- Expected: `<...server-groups] | [--[replace] | [--server-groups]] )>`

### Actual Result
- We get the failure:
- [ERROR] `testStandalone(org.jboss.as.cli.impl.aesh.HelpSupportTestCase)`  Time elapsed: 0.254 s  <<< FAILURE!
`org.junit.ComparisonFailure`: `org.jboss.as.cli.impl.aesh.Commands$Standalone$Command10`. EXPECTED `[command1 [<argument>] ( [--all-server-groups] | [--replace] | [--server-groups] )]`. FOUND `[command1 [<argument>] ( [--all-server-groups] | [--server-groups] | [--replace] )]` expected: `<...server-groups] | [--[replace] | [--server-groups]] )>` but was: `<...server-groups] | [--[server-groups] | [--replace]] )>`

### Fix
- Changed the `conflicts` and `conflicts2` objects from `HashSet` to `LinkedHashSet` in method `SynopsisGenerator.addSynopsisOption(SynopsisOption)` and imported `LinkedHashSet`.

This PR is similar to some merged PRs in other wildfly projects:

https://github.com/wildfly/wildfly/pull/13728
https://github.com/wildfly/wildfly/pull/11833
https://github.com/wildfly/jboss-ejb-client/pull/534

### Jira Issue: 
https://issues.redhat.com/browse/WFCORE-6214

2023-01-30 09:29 UTC, yersan commented
Hi @RishabhPrabhu5 , thank you for contributing to WildFly!

Could you add the Jira number to the commit message? Like what you did with the title, having the Jira number in the commit message is a requirement for us. It helps us to track the history with the Jira issue.

2023-01-30 10:50 UTC, jfdenise requested changes

2023-01-30 10:50 UTC, jfdenise commented on cli/src/main/java/org/jboss/as/cli/impl/aesh/SynopsisGenerator.java
> +            Set<SynopsisOption> conflicts2 = new LinkedHashSet<>(currentOption.conflictWith);
I think that the correct fix would be to use 
```
Set<SynopsisOption> conflicts2 = new TreeSet<>(Comparator.comparing(SynopsisOption::getName));
conflicts2.addAll(currentOption.conflictWith);
```
In order to iterate the conflicts using the natural ordering of Options (name).

2023-01-30 10:50 UTC, jfdenise commented on cli/src/main/java/org/jboss/as/cli/impl/aesh/SynopsisGenerator.java
> +            Set<SynopsisOption> conflicts = new LinkedHashSet<>(currentOption.conflictWith);
This change is not needed.

2023-01-30 10:54 UTC, jfdenise commented
@RishabhPrabhu5 thank-you for your fix. I added a comment.

Running your plugin I found another one in : https://github.com/wildfly/wildfly-core/blob/main/cli/src/test/java/org/jboss/as/cli/impl/BootScriptInvokerTestCase.java#L217
Should be a LinkedHashSet. Would you be ok to update the JIRA description and also fix this one? The JIRA would be the findings running the plugin against CLI unit tests.

Thank-you!

2023-02-11 01:17 UTC, RishabhPrabhu5 commented
Thank you for the feedback, I have made the changes requested and have updated the JIRA description. Please let me know if there is anything more I can do.
Thank you!

2023-02-13 13:01 UTC, yersan commented
/ok-to-test

2023-02-14 09:58 UTC, yersan commented
Windows - Bootable JAR - JDK 11 is unrelated to this PR.

2023-02-15 10:02 UTC, merged

2023-02-15 10:06 UTC, yersan commented
@RishabhPrabhu5 , merged!, thanks for contributing to WildFly, and especially for the great PR description, that helps in doing the review.

2023-02-15 11:18 UTC, RishabhPrabhu5 commented
Thank you for your email and accepting my PR. I hope my fix was useful, and
I look forward to contribute more in the future. Thanks!

On Wed, Feb 15, 2023 at 5:06 AM Yeray Borges ***@***.***>
wrote:

> @RishabhPrabhu5 <https://github.com/RishabhPrabhu5> , merged!, thanks for
> contributing to WildFly, and especially for the great PR description, that
> helps in doing the review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wildfly/wildfly-core/pull/5366#issuecomment-1431059020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYYIO436OBSDNIMQQNH5QDTWXSTCVANCNFSM6AAAAAAUKVD7EY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>