[WFCORE-5557} Remove setAllowNull deprecated API
wildfly/wildfly-core pull request #5378
Opened 2023-02-14 14:53 UTC by RoyalKarma

https://issues.redhat.com/browse/WFCORE-5557

2023-02-14 14:57 UTC, simkam requested changes

2023-02-14 14:57 UTC, simkam commented on controller/src/main/java/org/jboss/as/controller/AbstractAttributeDefinitionBuilder.java
please remove also one empty line

2023-02-14 15:04 UTC, simkam approved these changes

2023-02-15 09:46 UTC, yersan commented
/ok-to-test

2023-02-16 17:59 UTC, yersan approved these changes

2023-02-17 09:49 UTC, merged

2023-02-17 09:50 UTC, yersan commented
@RoyalKarma , thanks!