[WFCORE-6249] Eliminating deprecated sun.jdk module usages
wildfly/wildfly-core pull request #5445
Opened 2023-04-06 18:26 UTC by ropalka

https://issues.redhat.com/browse/WFCORE-6249

2023-04-12 09:50 UTC, yersan requested changes

2023-04-12 10:16 UTC, ropalka commented on testsuite/layers/src/test/java/org/jboss/as/test/layers/LayersTestCase.java
> +        "sun.jdk",
You are of course right @yersan . I noticed that too during the weekend when I was doing further WF sun.jdk cleanup.

2023-04-12 18:28 UTC, bstansberry requested changes

2023-04-12 18:28 UTC, bstansberry commented on core-feature-pack/common/src/main/resources/modules/system/layers/base/sun/scripting/main/module.xml
> +        <property name="jboss.api" value="deprecated"/>
I'm pretty sure we should not do this.

The "deprecated" setting means "'public' but be aware we might remove this some time". If this wasn't public before I don't know why it should become public now.

2023-04-17 09:19 UTC, ropalka commented
Hello @yersan this PR is awaiting your approval.

2023-04-17 10:41 UTC, yersan commented
Hi @ropalka , yes, I'm keeping an eye on it, we need to go with full confidence at this stage and "
Galleon Full integration - Linux" failed twice with your latest changes, apparently it is unrelated, but better to go with all in gree for now

2023-04-17 13:45 UTC, yersan approved these changes

2023-04-17 15:57 UTC, merged

2023-04-17 15:57 UTC, yersan commented
Thanks @ropalka