WFCORE-6331 Remove deprecated ProductConfig constructor
wildfly/wildfly-core pull request #5490
Opened 2023-05-03 17:52 UTC by parsharma

Issue: https://issues.redhat.com/browse/WFCORE-6331

2023-05-05 10:16 UTC, kabir commented
@parsharma Since the PatchInfoTestCase failures happen across a lot of the WFCOR test runs, it looks like perhaps the test needs adjusting for this change. Apart from that it looks good (i.e. the full integration tests work)

2023-05-08 10:39 UTC, yersan requested changes
@parsharma errors are legit, there is a reflection that invokes the constructor you have removed here:

https://github.com/wildfly/wildfly-core/blob/main/testsuite/patching/src/test/java/org/jboss/as/test/patching/ProductInfo.java#L36

As the Java doc states, you should change the reflection call to use `fromFilesystemSlot` instead

2023-05-10 06:10 UTC, parsharma commented on testsuite/patching/src/test/java/org/jboss/as/test/patching/ProductInfo.java
> +
Thanks @bstansberry, I have updated the imports.

2023-05-10 06:10 UTC, parsharma commented
Thanks, @yersan & @kabir for the review comments.

2023-05-10 15:47 UTC, yersan approved these changes

2023-05-10 16:02 UTC, merged

2023-05-10 16:03 UTC, yersan commented
Thanks @parsharma and @bstansberry / @kabir