[WFCORE-6349] Log yaml files used for configuration extension
wildfly/wildfly-core pull request #5582
Opened 2023-07-11 10:40 UTC by The-Huginn

[https://issues.redhat.com/browse/WFCORE-6349](https://issues.redhat.com/browse/WFCORE-6349)

2023-07-11 12:49 UTC, xstefank commented
/ok-to-test

2023-07-11 13:10 UTC, ehsavoie requested changes

2023-07-11 13:10 UTC, ehsavoie commented on controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
> +                    parsedFiles.add(file.toFile().getName());
It should put the absolute path if the gaol is to know which files were used

2023-07-11 13:10 UTC, ehsavoie commented on controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
> +        MGMT_OP_LOGGER.loadingYamlFiles(System.currentTimeMillis() - start, String.join(",", parsedFiles));
Why use a list for this since we know the number of files

2023-07-11 13:11 UTC, ehsavoie commented on controller/src/main/java/org/jboss/as/controller/logging/ControllerLogger.java
> +    @LogMessage(level = INFO)
This should be left in DEBUG

2023-07-28 13:35 UTC, yersan commented
@ehsavoie Do you agree with the current status?

2023-08-07 08:33 UTC, ehsavoie commented on controller/src/main/java/org/jboss/as/controller/persistence/yaml/YamlConfigurationExtension.java
> +        MGMT_OP_LOGGER.loadingYamlFiles(System.currentTimeMillis() - start, String.join(",", parsedFiles));
Ok, Let's keep the list
@yersan the extension is loaded only if there are configuration files

2023-08-11 13:53 UTC, ehsavoie approved these changes

2023-08-14 08:25 UTC, merged

2023-08-14 08:25 UTC, yersan commented
Thanks @The-Huginn and @ehsavoie