[WFCORE-6532] Add security manager to script tests
wildfly/wildfly-core pull request #5706
Opened 2023-10-10 11:16 UTC by xjusko

[https://issues.redhat.com/browse/WFCORE-6532](url)

2023-10-11 00:29 UTC, jamezp requested changes

2023-10-11 00:29 UTC, jamezp commented on testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
> +        boolean isSecurityManagerEnabled = Boolean.parseBoolean(System.getProperty("security.manager"));
IMO we should skip this check and just always test with the security manager enabled in one run. Currently we don't run security manager tests on Windows so we'd lose that testing.

2023-10-11 00:29 UTC, jamezp commented on testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
> +        return result;
This could simply be `return List.of(Map.of(), Map.of("SECMGR", "true"));`.

2023-10-11 00:29 UTC, jamezp commented on testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
> +        boolean isSecurityManagerEnabled = Boolean.parseBoolean(System.getProperty("security.manager"));
Same here, we should always do a run with the security manager enabled.

2023-10-11 17:08 UTC, jamezp requested changes

2023-10-11 17:08 UTC, jamezp commented on testsuite/scripts/src/test/java/org/wildfly/scripts/test/DomainScriptTestCase.java
> +        modifiedJavaOpts[modifiedJavaOpts.length - 1] = "-secmgr";
Sorry, I was clear with my wording here. We shouldn't be adding the `-secmgr` parameter to the server arguments if we've already got it set in the environment variable. Essentially we could just do this:
```java
script.start(HOST_CONTROLLER_CHECK, env, ServerHelper.DEFAULT_SERVER_JAVA_OPTS);
```

2023-10-12 05:52 UTC, xjusko commented
I see, no problem, it should be fixed now.
Thanks for your help.

2023-10-12 16:45 UTC, jamezp requested changes

2023-10-12 16:45 UTC, jamezp commented on testsuite/scripts/src/test/java/org/wildfly/scripts/test/StandaloneScriptTestCase.java
> +import java.util.Arrays;
This is also causing a checkstyle issue and should be removed.

2023-10-13 00:48 UTC, jamezp approved these changes

2023-10-16 13:44 UTC, merged

2023-10-16 13:44 UTC, yersan commented
Thanks @xjusko @jamezp