[WFCORE-6712] Ensure the JBoss Modules ModuleLoggerFinder is activate…
wildfly/wildfly-core pull request #5882
Opened 2024-02-23 02:03 UTC by jamezp

…d after the log manager is configured.

https://issues.redhat.com/browse/WFCORE-6712

2024-02-26 09:42 UTC, yersan commented
Ok, @jamezp , let's wait a bit for MODULES-447 decision

2024-02-26 16:31 UTC, jamezp commented
> Ok, @jamezp , let's wait a bit for MODULES-447 decision

@yersan It looks like for now, [reflection](https://github.com/jboss-modules/jboss-modules/pull/329#discussion_r1502761692) is the way to go.

2024-02-26 23:43 UTC, bstansberry requested changes
@jamezp  The change looks fine but I think this should have a regression test.

2024-02-27 01:46 UTC, jamezp commented
> @jamezp The change looks fine but I think this should have a regression test.

That's a good point. Let me see if I can think of a way to do that.

2024-02-28 19:24 UTC, jamezp commented
Regression tests added.

2024-03-01 11:15 UTC, yersan approved these changes

2024-03-01 12:13 UTC, merged

2024-03-01 12:13 UTC, yersan commented
Thanks @jamezp @bstansberry