[WFCORE-6834] wildfly-elytron-integration jar duplicated in server modules
wildfly/wildfly-core pull request #6067
Opened 2024-07-10 12:55 UTC by yersan

Jira issue: https://issues.redhat.com/browse/WFCORE-6834

2024-07-11 15:19 UTC, bstansberry requested changes
Thanks @yersan. The change is fine but since this is really strange stuff I think a comment is needed.

2024-07-11 15:21 UTC, bstansberry commented on core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/jaas-realm/main/module.xml
> +                <exclude path="org/wildfly/extension/elytron/*"/>
When you add a comment please don't block on me to re-review. I will if I notice, but we're close to the release so I don't want to delay your work on it.

2024-07-11 15:49 UTC, yersan commented on core-feature-pack/common/src/main/resources/modules/system/layers/base/org/wildfly/extension/elytron/jaas-realm/main/module.xml
> +                <exclude path="org/wildfly/extension/elytron/*"/>
Done

2024-07-12 08:53 UTC, merged

2024-07-12 08:53 UTC, yersan commented
Thanks @ivassile @bstansberry