[WFCORE-6976] acmeAccount variable is not being used
wildfly/wildfly-core pull request #6158
Opened 2024-09-02 18:29 UTC by pedro-hos

[WFCORE-6976]  acmeAccount variable is not being used on CertificateAuthoritiesTestCase.java class

2024-09-03 12:31 UTC, yersan requested changes
Thanks for contributing to WildFly Core @pedro-hos !

Indeed, there is also another line to be removed at L397
https://github.com/wildfly/wildfly-core/blob/035d41260346840f0073a90875997f2b8f16df17/elytron/src/test/java/org/wildfly/extension/elytron/CertificateAuthoritiesTestCase.java#L397

Would you mind removing it as well and adding the Jira link to the PR description?

Just FYI, more information about how to contribute can be found here: https://docs.wildfly.org/33/Hacking_On_WildFly.html#describe-the-pull-request-adequately

2024-09-04 12:51 UTC, pedro-hos commented
Hi @yersan I've made the changes and removed the other unused variable. Thank you

2024-09-05 11:38 UTC, yersan commented
"Galleon Full integration - Linux" error is unrelated to this PR

2024-09-05 11:40 UTC, yersan approved these changes

2024-09-05 11:44 UTC, merged

2024-09-05 11:45 UTC, yersan commented
Thanks @pedro-hos !