[WFCORE-7102]: AccessDeniedException on Windows when using a read-only
wildfly/wildfly-core pull request #6287
Opened 2024-12-17 16:48 UTC by ehsavoie

configuration dir.

* Replacing java.io.File.canWrite() by java.nio.file.FIles.isWritable(Path).

Jira: https://issues.redhat.com/browse/WFCORE-7102

2024-12-17 16:52 UTC, yersan commented
thanks @ehsavoie , Ideally, we should enable this test for Windows with this PR: https://github.com/wildfly/wildfly-core/blob/main/testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java#L72-L74

But I know there are currently issues setting a read-only directory in the code since the CI won't be able to delete it. We can discuss it with @luck3y if there is any way to enable that permissions for Windows OS

2024-12-17 23:47 UTC, luck3y commented
Hi Yeray,

You should be able to create a directory in Windows and mark it read only,
ideally reversing the read only bit when the test is done. I don't think
any special permissions are required as long as you stay within the
checkout directory in CI.

Ken

On Tue, Dec 17, 2024, 10:53 Yeray Borges ***@***.***> wrote:

> thanks @ehsavoie <https://github.com/ehsavoie> , Ideally, we should
> enable this test for Windows with this PR:
> https://github.com/wildfly/wildfly-core/blob/main/testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java#L72-L74
>
> But I know there are currently issues setting a read-only directory in the
> code since the CI won't be able to delete it. We can discuss it with
> @luck3y <https://github.com/luck3y> if there is any way to enable that
> permissions for Windows OS
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wildfly/wildfly-core/pull/6287#issuecomment-2549020001>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC7HAFYPUJN7DZHZDR5AGD2GBJHXAVCNFSM6AAAAABTY25IICVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNBZGAZDAMBQGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-18 12:37 UTC, yersan commented
Weird, test still appears as ignored in Windows: https://ci.wildfly.org/buildConfiguration/WildFlyCore_PullRequest_WindowsJdk11/476232?buildTab=tests&name=ReadOnlyModeTestCase&suite=&package=org.jboss.as.test.manualmode.management

WDYT @ehsavoie ?

2024-12-18 17:55 UTC, ehsavoie commented
@yersan This is properly fixed now and it works

2025-01-14 20:44 UTC, bstansberry requested changes
I've made some trivial change requests. I've not tried to understand the meat of this, so please don't regard fixing my requests as an approval; rely on the others who are reviewing.

OTOH, mergers please don't block on my re-reviewing my trivial items before merging.

2025-01-14 20:44 UTC, bstansberry commented on server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java
> +        ServerLogger.ROOT_LOGGER.warn("Reloading with config file " + serverConfig);
@ehsavoie Please remove. I assume this is test cruft.

2025-01-14 20:44 UTC, bstansberry commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
>  import jakarta.inject.Inject;
This goes after java.xxx

2025-01-14 20:44 UTC, bstansberry commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
> +        }
The identation from R150-R161 is off.

2025-01-14 20:45 UTC, bstansberry commented
@luck3y Please review.

2025-01-14 21:12 UTC, luck3y requested changes

2025-01-14 21:12 UTC, luck3y commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
> +        if (TestSuiteEnvironment.isWindows()) {
This seems odd to me, for Windows an ACL is constructed that denies the listed permissions, which seems correct, but on all other OSes are added as allowed. I'm probably missing something here though?

2025-01-14 21:12 UTC, luck3y commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
> +            if( TestSuiteEnvironment.isWindows()) {
I think the delete should be left out, as long as the permissions are reset this will get deleted by normal cleanup and shouldn't have any issues, and a recursive delete floating around on windows gives me the heebee-jeebies :)

2025-01-15 15:21 UTC, ehsavoie commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
> +            if( TestSuiteEnvironment.isWindows()) {
ok, removed

2025-01-15 15:21 UTC, ehsavoie commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
> +        }
fixed

2025-01-15 15:22 UTC, ehsavoie commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
>  import jakarta.inject.Inject;
ok

2025-01-15 15:22 UTC, ehsavoie commented on server/src/main/java/org/jboss/as/server/operations/ServerProcessReloadHandler.java
> +        ServerLogger.ROOT_LOGGER.warn("Reloading with config file " + serverConfig);
correct

2025-01-22 10:35 UTC, yersan commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
> +        if (TestSuiteEnvironment.isWindows()) {
@ehsavoie FYI ^^^

2025-01-22 13:59 UTC, ehsavoie commented on testsuite/manualmode/src/test/java/org/jboss/as/test/manualmode/management/ReadOnlyModeTestCase.java
> +        if (TestSuiteEnvironment.isWindows()) {
Well 1st, I only looked at Windows but the problem is that the permissions are quite complex with a lot of principals so I reduced the change to the owner only and removing a permission isn't sufficient in Windows you have to DENY it.

2025-01-28 13:19 UTC, yersan approved these changes
LGTM, @luck3y Do you have any additional review from your side?

2025-01-28 23:53 UTC, luck3y commented
> LGTM, @luck3y Do you have any additional review from your side?

LGTM too, I looked at the code again, its only adding read and execute, no write, so I must have misread it the first time.

2025-01-28 23:54 UTC, luck3y approved these changes

2025-01-30 11:24 UTC, merged

2025-01-30 11:25 UTC, yersan commented
Thanks @ehsavoie @luck3y @bstansberry