[WFCORE-7105] Use ModuleDependency.Builder instead of deprecated ModuleDependency ctor in Server
wildfly/wildfly-core pull request #6292
Opened 2024-12-18 20:03 UTC by ropalka

https://issues.redhat.com/browse/WFCORE-7107

2024-12-19 13:54 UTC, bstansberry commented
Hi @ropalka Please reopen when nearly all the 35.x PRs in WildFly are merged.

2024-12-22 20:25 UTC, bstansberry requested changes

2024-12-22 20:25 UTC, bstansberry commented on server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
> +                final ModuleDependency dependency = ModuleDependency.Builder.of(dependencyLoader, dependencyId.toString()).setOptional(optional).setExport(export).setImportServices(services).build();
This needs .setUserSpecified(true)

2025-01-03 18:28 UTC, ropalka commented on server/src/main/java/org/jboss/as/server/deployment/module/ManifestDependencyProcessor.java
> +                final ModuleDependency dependency = ModuleDependency.Builder.of(dependencyLoader, dependencyId.toString()).setOptional(optional).setExport(export).setImportServices(services).build();
Good catch! It is fixed now @bstansberry .

2025-01-14 20:33 UTC, bstansberry approved these changes

2025-01-14 20:34 UTC, merged